### get all persons
GET http://localhost:3001/api/persons

### Add new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Dil",
  "number": "041-12345612"
}

### Get single person
GET http://localhost:3001/api/persons/65950b8b7b8bea7d78b08b02
